# Skills required for different job roles

ROLE_SKILLS = {
    "AI Engineer": {
        "Python": 85,
        "Machine Learning": 90,
        "Deep Learning": 85,
        "PyTorch": 80,
        "TensorFlow": 70,
        "SQL": 70,
        "Statistics": 75,
        "Git": 65,
        "Docker": 65,
        "Computer Vision": 70,
        "NLP": 65,
        "APIs": 60,
    },
    "Machine Learning Engineer": {
        "Python": 90,
        "Machine Learning": 95,
        "Deep Learning": 85,
        "PyTorch": 85,
        "TensorFlow": 80,
        "SQL": 70,
        "Statistics": 80,
        "Git": 70,
        "Docker": 75,
        "APIs": 65,
    },
    "Frontend Developer": {
        "HTML": 85,
        "CSS": 85,
        "JavaScript": 90,
        "React": 85,
        "TypeScript": 75,
        "Git": 70,
        "REST APIs": 65,
        "Responsive Design": 80,
        "Testing": 60,
        "UI/UX": 65,
    },
    "Backend Developer": {
        "Python": 75,
        "Java": 70,
        "Node.js": 80,
        "SQL": 85,
        "REST APIs": 85,
        "Git": 70,
        "Docker": 70,
        "Database Design": 75,
        "Authentication": 65,
        "Testing": 60,
    },
    "Data Scientist": {
        "Python": 90,
        "SQL": 80,
        "Statistics": 90,
        "Machine Learning": 85,
        "Pandas": 85,
        "NumPy": 80,
        "Data Visualization": 75,
        "Deep Learning": 60,
        "Git": 60,
    },
    "Robotics Engineer": {
        "Python": 75,
        "C++": 85,
        "ROS": 85,
        "Robotics": 90,
        "Computer Vision": 80,
        "Control Systems": 75,
        "Embedded Systems": 75,
        "Linux": 70,
        "Git": 65,
        "Sensors": 75,
    },
}
